DELETE http://localhost:3003/api/blogs/6468fc64d904a0fa460c0bc2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2NDY4ZjM2NWFmN2FhMTcwMjBkNmZkNDQiLCJpYXQiOjE2ODQ2MDA4MTN9.MVDOhdzQcA9gBLGU7aqcR8JtELT1pbtSNhGMMtDBUfs
